### ISSUE TITLE
Unable to run the scraper : Apify.main() threw an exception

### ISSUE THREAD

**Issue by kaislar** [maxCopell/tripadvisor-scraper#10]
Hello, 
I am trying to run the script on Apitfy plateform. I got this error. 

`2020-09-13T07:44:10.864Z ERROR The function passed to Apify.main() threw an exception:
2020-09-13T07:44:10.866Z   TypeError: Cannot read property 'data' of undefined
2020-09-13T07:44:10.867Z       at getLocationId (/usr/src/app/src/tools/api.js:58:29)
2020-09-13T07:44:10.869Z       at processTicksAndRejections (internal/process/task_queues.js:97:5)
`
No proxy is used, I selected a city and a date as input. 
Thank you. 
Thanks.

**Comment by metalwarrior665** [comment]
It is a bug because the SHADER proxy is forced here.

**Comment by kaislar** [comment]
Any idea how to solve it?

**Comment by metalwarrior665** [comment]
The fix is in PR, waiting for Max to merge.

**Comment by metalwarrior665** [comment]
This fix is on

**Comment by kaislar** [comment]
@metalwarrior665 I still get the same error when using the GOOGLE_SERP. Is there a way to get it working with custom proxies ? I think now it only supports automatic apify proxies. Thanks

**Comment by metalwarrior665** [comment]
Only Apify proxies are permitted right now. And GOOGLE_SERP doesn't work for obvious reasons. We will refactor it to allows custom proxies in the future.
