### ISSUE TITLE
Actor sometimes hangs on

### ISSUE THREAD

**Issue by metalwarrior665** [maxCopell/tripadvisor-scraper#12]
Run with this input hanged for 6 minutes with 5 requests still in the queue.

```
{
  "lastReviewDate": "2019-06-06",
  "locationFullName": "Como",
  "includeRestaurants": true,
  "includeAttractions": false,
  "includeHotels": false,
  "includeReviews": false,
  "proxyConfiguration": {
    "useApifyProxy": true
  },
  "locationId": ""
}
```

**Comment by metalwarrior665** [comment]
Should remove the `minConcurrency` and add `desiredConcurrency`. But the bug might be also in some of promise handling.

**Comment by pocesar** [comment]
still happening, looks like the browser is not being retired properly on max redirect errors

**Comment by pocesar** [comment]
this is fixed, but the search should be also fixed, works only with locationId right now
