### ISSUE TITLE
Default run is missing

### ISSUE THREAD

**Issue by zpelechova** [maxCopell/tripadvisor-scraper#17]
I would very much appreciate if when I open a task could just run it to see if the actor is working.

**Comment by dtrungtin** [comment]
Set "Prague" as default.

**Comment by dtrungtin** [comment]
Can add me as Collaborator so I can set Label?

**Comment by pocesar** [comment]
the search is not working right now, requires a locationId, at least

**Comment by dtrungtin** [comment]
I am going to add default value for locationFullName instead of locationId. What do you think?
    "locationFullName": {
      "title": "Location",
      "type": "string",
      "description": "Location name as you would enter to TripAdvisor search. Actor takes the first result as desired location",
      "default": "Prague",
      "prefill": "Prague",
      "editor": "textfield"
    },

**Comment by pocesar** [comment]
it's broken, the endpoint that it calls doesn't work

**Comment by dtrungtin** [comment]
I see you have changed getLocationId function; however, I have tried and it's not working. Could I roll back to the previous function to use the old endpoint?

Regarding to the old endpoint, it will work fine if changing http method from POST to GET. I think it's recent changes from tripadvisor.
