### ISSUE TITLE
Wasting CUs?

### ISSUE THREAD

**Issue by zpelechova** [maxCopell/tripadvisor-scraper#25]
It runs very fast at the beginning (Almost till the end), then it gets stuck on last 5 results or so for next 15 hrs and 50Cus -  it would be great to have the actor stopped.
Compare long run:
https://my.apify.com/view/runs/2kZ84ZYGtFspOcSk3
Short run (aborted): https://my.apify.com/view/runs/nBU6aToV1BAFWsLeF

**Comment by pocesar** [comment]
fixed on #31
