### ISSUE TITLE
Cannot scrape restaurants anymore

### ISSUE THREAD

**Issue by terjeterje2021** [maxCopell/tripadvisor-scraper#35]
Hi, 

I've been using the tripadvisor scraper for restaurants and would always uncheck hotels and didn't need to enter a check in date. Since the last time I used it I am required to enter a check in date even though I don't need the hotel data. Whichever city I try to run I get the same error: "The main function of the actor threw an exception." 

Not very technical so hope my explanation makes sense

**Comment by terjeterje2021** [comment]
Hi again, I've checked with several colleagues in my organization and they have the same issues with the same error message. So not sure if it's due to an update but currently we can't scrape the restaurant data.

**Comment by pocesar** [comment]
hey @terjeterje2021 can you provide the input you used?

**Comment by pocesar** [comment]
it was the `pattern` property on the schema, when it's present it considers the field as "required". I've removed it
