### ISSUE TITLE
Didnt get enough reviews

### ISSUE THREAD

**Issue by zpelechova** [maxCopell/tripadvisor-scraper#36]
the actor gets e.g. reviewsCoun of 232 but no or 1-3 reviews: https://my.apify.com/view/runs/nj1HEvPwWItcEQZWH

**Comment by dtrungtin** [comment]
You set "lastReviewDate": "2021-01-01" so only crawling the reviews from 2021-01-01 to now.

**Comment by gustavotr** [comment]
I have opened a PR #60 that changes the way to get the reviews
