### ISSUE TITLE
Mealtypes always empty

### ISSUE THREAD

**Issue by zpelechova** [maxCopell/tripadvisor-scraper#45]
https://my.apify.com/view/runs/xjSL8NoNUNGruOWAz

**Comment by gustavotr** [comment]
Is there any example of what kind of information these field was displaying? I think it is not present on the result anymore but maybe it has a new name. I think these could be the replacement:
```js
dietary_restrictions: [
    { key: '10665', name: 'Vegetarian Friendly' },
    { key: '10697', name: 'Vegan Options' },
    { key: '10992', name: 'Gluten Free Options' }
  ],
```

**Comment by zpelechova** [comment]
Frankly, no idea, I tried to find when it changed in the code, bcs in my runs from March/April, it is not there, but was not succesfull. Can you find it in the commits? Otherwise we can just close the issue or add the thing you are suggesting, it seems really nice enhancement.
