### ISSUE TITLE
Attractions/thingsToDo dont work

### ISSUE THREAD

**Issue by zpelechova** [maxCopell/tripadvisor-scraper#46]
https://my.apify.com/view/runs/Ty8iHOGDZqREnrFyD
For some reason it works for Roudnice - https://my.apify.com/view/runs/RDXLjblSBy4lTHiCQ ?

**Comment by zpelechova** [comment]
Funnily enought seems to be working on smaller cities (regional) and not big like Prague or New York.

**Comment by zpelechova** [comment]
And it has ranking three times :D 
![image](https://user-images.githubusercontent.com/39551460/124898601-a4c4e400-dfdf-11eb-908f-424cdf65aee7.png)

**Comment by gustavotr** [comment]
> And it has ranking three times :D
> ![image](https://user-images.githubusercontent.com/39551460/124898601-a4c4e400-dfdf-11eb-908f-424cdf65aee7.png)

This is the data in the response got from the TripAdvisor API. It might return different results in some cases.
