### ISSUE TITLE
handleRequestFunction failed

### ISSUE THREAD

**Issue by simonemonetti** [maxCopell/tripadvisor-scraper#6]
Hi there, 
first of all congrats on the amazing work you've done so far.
When searching for restaurants, I'm suddenly encountering an issue which doesn't allow the scraper to return a lot of data.
I tried with different cities as input but still this keeps on happening.

Here's the error details:

`ERROR: BasicCrawler: handleRequestFunction failed, reclaiming failed request back to the list or queue
TypeError: Cannot read property 'replace' of null
at getSecurityToken (/usr/src/app/src/tools/general.js:33:26)
at getClient (/usr/src/app/src/tools/general.js:197:31)`

Thanks in advance

**Comment by maxCopell** [comment]
Hi there,
Thanks!
Tripadvisor changed the website slightly, so I need to do some adjustments here. Expecting to have fixed version soon.

**Comment by dtrungtin** [comment]
I think the issue has been fixed. Please double-check.
