### ISSUE TITLE
Milan City Center scraper error

### ISSUE THREAD

**Issue by progettoautomazione** [maxCopell/tripadvisor-scraper#67]
Hi, we are trying to scrape restaurants for this location https://www.tripadvisor.it/Restaurants-g187849-zfn8117507-Milan_Lombardy.html that in Tripadvisor is called Milan City Center (Milano Centro Storico in Italian). But I'm getting error. I guess he cannot find this location, but the weird thing is that in Tripadviso exsists. Any suggestion on how to scrape this location?

Thanks

**Comment by HALAMHA** [comment]
Hi, this actor needs to fixed and it is in progress already. We will let you know once we have an update (probably within next week).

**Comment by progettoautomazione** [comment]
Ah ok! I was getting crazy! Is there a previous build that I can use or this bug affects all builds? Please let me know when fixed because I've my workflows blocked. Appreciated

**Comment by zpelechova** [comment]
Hey, should be working now seamlessly, can you try out?
@progettoautomazione

**Comment by progettoautomazione** [comment]
> Hey, should be working now seamlessly, can you try out? @progettoautomazione

Hi, I tried and it's getting better but the task is not ending and keep giving these errors https://www.loom.com/share/743b765472494f88859365274dfaf114
